config/routes.rb
Rails.application.routes.draw do
  resource :scraps, only: [:new, :create]
  root 'scraps#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/scraps_controller.rb
class ScrapsController < ApplicationController
  require 'booking_search'
  def new
    @form = Struct.new(:city, :checkin, :checkout)
  end

  def create
    @booking = BookingSearch.perform(params[:city], params[:checkin], params[:checkout])
    render json: @booking.to_json
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scraps_helper.rb
module ScrapsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scrub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scraps/new.html.slim
.container
  br
  h3 Booking
  hr
  br
  br
  br

  .form-container
    = form_tag(scraps_path, method: 'post', id: 'searchBooking', data: { type: :json, remote: true } ) do
      .input-field
        = text_field_tag  :city
        = label_tag :city, 'Місто'
      .input-field
        = text_field_tag  :checkin
        = label_tag :checkin, 'З якого: дд.мм.рррр'
      .input-field
        = text_field_tag  :checkout
        = label_tag :checkout, 'По яке: дд.мм.рррр'
      button#searchSubmit.btn
        span Шукати

  #searchData

  =render 'shared/search_btn', target: '#searchBooking', id: 'searchBtn'

app/views/shared/_search_btn.html.slim
.fixed-action-btn style="bottom: 45px; right: 24px;" id="#{ local_assigns.fetch(:id, nil) }"
  button.btn-floating.btn-large.red.script-item-toggle data-target="#{ local_assigns.fetch(:target, nil) }"
    i.large.material-icons search

app/views/static_pages/home.html.slim
.container
  h1 Hello